[tool.briefcase]
project_name = "InfomationHiding"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/infomationhiding"
license = "BSD license"
author = 'Nhom 3'
author_email = "loanphuongg2.7@gmail.com"

[tool.briefcase.app.infomationhiding]
formal_name = "InfomationHiding"
description = "Ung dung giau tin trong anh"
icon = "src/infomationhiding/resources/infomationhiding"
sources = ['src/infomationhiding']
requires = [
]


[tool.briefcase.app.infomationhiding.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.infomationhiding.linux]
requires = [
    'toga-gtk>=0.3.0.dev32',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.infomationhiding.windows]
requires = [
    'toga-winforms>=0.3.0.dev32',
]

# Mobile deployments
[tool.briefcase.app.infomationhiding.iOS]
requires = [
    'toga-iOS>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.infomationhiding.android]
requires = [
    'toga-android>=0.3.0.dev32'
]
